apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest # Replace with your Docker image reference
        env:
          - name: ORDER_SERVICE_URL
            value: http://order-service:80 # Internal communication with the Order Service
